
POST http://localhost:8080/v1/fragments
Content-Type: application/json
[BasicAuth]
user1@email.com: password1
```
{
  "type": "json type",
  "content": "Hello, world!"
}
```

HTTP/1.1 201
[Asserts]
jsonpath "$.status" == "ok"
jsonpath "$.status" == "ok"
jsonpath "$.fragment.type" == "application/json"

header "Location" matches "^http:\/\/localhost:8080\/v1\/fragments\/[A-Za-z0-9_-]+$"
jsonpath "$.fragment.id" matches "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
jsonpath "$.fragment.ownerId" matches "^[0-9a-fA-F]+$"
jsonpath "$.fragment.created" isString
jsonpath "$.fragment.updated" isString
jsonpath "$.fragment.size" == 56


[Captures]
url: header "Location"

GET {{url}}
[BasicAuth]
user1@email.com: password1

HTTP/1.1 200
Content-Type: application/json
Content-Length: 56
[Asserts]
body == ```
{
  "type": "json type",
  "content": "Hello, world!"
}
```
